// Editing schemas for the three content datasets. The generic CollectionEditor
// renders these: a top-level list of items, each with simple fields plus an
// optional nested child list (tiles / days / questions). Anything not covered
// by a schema field stays untouched on save — and is still reachable through
// the Raw JSON tab.

const slug = (prefix) => `${prefix}-${Math.random().toString(36).slice(2, 8)}`

export const DATASET_SCHEMAS = {
  explore: {
    label: 'Explore',
    description: 'Themes and the article/video tiles shown on the Explore tab.',
    getList: (doc) => doc?.explore?.themes ?? [],
    setList: (doc, list) => ({ ...doc, explore: { ...(doc?.explore ?? {}), themes: list } }),
    itemName: 'theme',
    itemLabel: (t) => t.title || t.id || 'Untitled theme',
    newItem: () => ({
      id: slug('theme'),
      title: '',
      description: '',
      color: '#7F77DD',
      bg: '#EEEDFE',
      icon: 'ti-heart',
      content: [],
    }),
    fields: [
      { key: 'id', label: 'ID', type: 'text', hint: 'Unique slug — used in deep links (?theme=…)' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'color', label: 'Accent colour', type: 'color' },
      { key: 'bg', label: 'Background colour', type: 'color' },
      { key: 'icon', label: 'Icon', type: 'text', hint: 'Tabler icon name, e.g. ti-moon' },
    ],
    children: {
      key: 'content',
      label: 'Tiles',
      itemName: 'tile',
      itemLabel: (c) => c.title || c.id || 'Untitled tile',
      newItem: () => ({
        id: slug('item'),
        type: 'article',
        title: '',
        description: '',
        source: '',
        url: '',
        read_time_mins: 5,
      }),
      fields: [
        { key: 'id', label: 'ID', type: 'text' },
        { key: 'type', label: 'Type', type: 'select', options: ['article', 'video'] },
        { key: 'title', label: 'Title', type: 'text' },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'source', label: 'Source', type: 'text', hint: 'Shown as the publisher, e.g. TED, Mind UK' },
        { key: 'url', label: 'Link URL', type: 'text', placeholder: 'https://…' },
        { key: 'read_time_mins', label: 'Read time (mins)', type: 'number', hint: 'For articles' },
        { key: 'duration_mins', label: 'Duration (mins)', type: 'number', hint: 'For videos' },
      ],
    },
  },

  journeys: {
    label: 'Journeys',
    description: '30-day programmes and their daily tasks.',
    getList: (doc) => doc?.journeys ?? [],
    setList: (doc, list) => ({ ...doc, journeys: list }),
    itemName: 'journey',
    itemLabel: (j) => j.title || j.id || 'Untitled journey',
    newItem: () => ({
      id: slug('journey'),
      title: '',
      description: '',
      duration_days: 30,
      color: '#7F77DD',
      icon: 'ti-map',
      days: [],
    }),
    fields: [
      { key: 'id', label: 'ID', type: 'text', hint: 'Unique slug — used in deep links (?journey=…)' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'duration_days', label: 'Duration (days)', type: 'number' },
      { key: 'color', label: 'Accent colour', type: 'color' },
      { key: 'icon', label: 'Icon', type: 'text', hint: 'Tabler icon name' },
    ],
    children: {
      key: 'days',
      label: 'Days',
      itemName: 'day',
      itemLabel: (d) => (d.day != null ? `Day ${d.day} — ${d.title || ''}` : d.title || 'New day'),
      newItem: () => ({
        day: 1,
        type: 'read',
        title: '',
        task: '',
        source_title: null,
        source_url: null,
        reflection: null,
      }),
      fields: [
        { key: 'day', label: 'Day number', type: 'number' },
        { key: 'type', label: 'Type', type: 'select', options: ['read', 'watch', 'reflect', 'practice'] },
        { key: 'title', label: 'Title', type: 'text' },
        { key: 'task', label: 'Task', type: 'textarea' },
        { key: 'source_title', label: 'Source title', type: 'text', hint: 'Optional — label of the linked resource' },
        { key: 'source_url', label: 'Source URL', type: 'text', placeholder: 'https://…' },
        { key: 'reflection', label: 'Reflection prompt', type: 'textarea', hint: 'Optional' },
      ],
    },
  },

  assessments: {
    label: 'Assessments',
    description: 'Self-check questionnaires: card details, instructions and questions.',
    advancedNote:
      'Response scales, scoring bands, result texts and safety screens are clinical logic — edit those in the Raw JSON tab.',
    getList: (doc) => doc?.assessments ?? [],
    setList: (doc, list) => ({ ...doc, assessments: list }),
    itemName: 'assessment',
    itemLabel: (a) => a.title || a.id || 'Untitled assessment',
    newItem: () => ({
      id: slug('assessment'),
      title: '',
      subtitle: '',
      description: '',
      instrument: '',
      color: '#7F77DD',
      bg: '#EEEDFE',
      icon: 'ti-clipboard',
      time_mins: 2,
      retake_after_days: 14,
      disclaimer: '',
      instructions: '',
      response_scale: [
        { label: 'Not at all', value: 0 },
        { label: 'Several days', value: 1 },
        { label: 'More than half the days', value: 2 },
        { label: 'Nearly every day', value: 3 },
      ],
      questions: [],
      scoring: { type: 'sum', min: 0, max: 0 },
      results: [],
    }),
    fields: [
      { key: 'id', label: 'ID', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'instrument', label: 'Instrument', type: 'text', hint: 'e.g. GAD-7 (public domain)' },
      { key: 'color', label: 'Accent colour', type: 'color' },
      { key: 'bg', label: 'Background colour', type: 'color' },
      { key: 'icon', label: 'Icon', type: 'text' },
      { key: 'time_mins', label: 'Time (mins)', type: 'number' },
      { key: 'retake_after_days', label: 'Retake after (days)', type: 'number' },
      { key: 'disclaimer', label: 'Disclaimer', type: 'textarea' },
      { key: 'instructions', label: 'Instructions', type: 'textarea' },
    ],
    children: {
      key: 'questions',
      label: 'Questions',
      itemName: 'question',
      itemLabel: (q) => q.text || q.id || 'New question',
      newItem: () => ({ id: slug('q'), text: '' }),
      fields: [
        { key: 'id', label: 'ID', type: 'text' },
        { key: 'text', label: 'Question text', type: 'textarea' },
      ],
    },
  },
}
